name: Test de compilación

on:
  push:
    branches: [ "feature/makefile" ]
  pull_request:
    branches: [ "feature/makefile" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Clonar so-commons-library
      uses: actions/checkout@v3
      with:
        repository: sisoputnfrba/so-commons-library
        ref: master
        path: commons

    - name: Instalar so-commons-library
      run: |
        cd commons
        sudo make install

    - name: Clonar so-commons-library
      uses: actions/checkout@v3
      with:
        repository: sisoputnfrba/tp-2024-1c-Operativos-y-los-Redonditos-de-Ricota
        ref: feature/makefile
        path: tp

    - name: Probar compilacion correcta
      run: |
        cd tp
        make compile
