name: Test de compilación

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Clonar so-commons-library
      uses: actions/checkout@v3
      with:
        repository: sisoputnfrba/so-commons-library
        ref: master
        path: commons

    - name: Instalar so-commons-library
      run: |
        cd commons
        sudo make install

    - name: Clonar repositorio del TP
      uses: actions/checkout@v3
      with:
        repository: sisoputnfrba/tp-2024-1c-Operativos-y-los-Redonditos-de-Ricota
        ref: ${{ github.event.pull_request.head.ref || github.ref }}
        path: tp

    - name: Probar compilacion correcta del TP
      run: |
        cd tp
        make compile
