name: (pull_request) Verificaciones automáticas

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Clonar so-commons-library
      uses: actions/checkout@v3
      with:
        repository: sisoputnfrba/so-commons-library
        ref: master
        path: commons

    - name: Instalar so-commons-library
      run: |
        cd commons
        sudo make install
    - name: Clonar mumuki/cspec
      uses: actions/checkout@v3
      with:
        repository: mumuki/cspec
        ref: master
        path: cspec

    - name: Instalar mumuki/cspec
      run: |
        cd cspec
        sudo make install
    
    - name: Clonar repositorio del TP
      uses: actions/checkout@v3
      with:
        repository: sisoputnfrba/tp-2024-1c-Operativos-y-los-Redonditos-de-Ricota
        ref: ${{ github.head_ref }}
        path: tp

    - name: Probar compilacion correcta del TP
      run: |
        cd tp
        make compile
    - name: Ejecutar tests de todos los modulos
      run: |
        cd tp
        make test
